services:
  kyc-admin-frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_KYC_API_URL: https://kyc.apprain.ca

    container_name: kyc-admin-frontend
    restart: unless-stopped

    ports:
      - "127.0.0.1:3003:3003"

    environment:
      NEXT_PUBLIC_KYC_API_URL: https://kyc.apprain.ca