"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { saveAs } from "file-saver";

const API_URL = process.env.NEXT_PUBLIC_API_URL;

export default function BrokerageApplicationDetailPage() {
  const params = useParams();
  const leadId = params.id as string;

  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [lead, setLead] = useState<any>(null);
  const [extraData, setExtraData] = useState<any>(null);
  const [kycData, setKycData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadLead() {
      try {
        const res = await fetch(`${API_URL}/api/leads/${leadId}`);
        const data = await res.json();

        const kycRes = await fetch(`${API_URL}/api/leads/${leadId}/kyc-data`);
        const kyc = await kycRes.json();

        if (kycRes.ok) {
          setKycData(kyc);
        }

        setLead(data.lead);
        setExtraData(data.extraData?.data || null);
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    }

    loadLead();
  }, [leadId]);

  async function approveApplication() {
    await fetch(`${API_URL}/api/brokerage/${leadId}/approve`, {
      method: "POST",
    });

    window.location.reload();
  }

  async function rejectApplication() {
    await fetch(`${API_URL}/api/brokerage/${leadId}/reject`, {
      method: "POST",
    });

    window.location.reload();
  }

  async function downloadApplicationPdf() {
    const pdfDoc = await PDFDocument.create();

    const pageWidth = 595;
    const pageHeight = 842;

    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = 800;

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    function text(value: any) {
      return String(value || "-");
    }

    function addNewPage() {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      y = 800;
    }

    function ensureSpace(requiredHeight = 80) {
      if (y < requiredHeight) {
        addNewPage();
      }
    }

    function drawTitle(title: string) {
      page.drawText(title, {
        x: 40,
        y,
        size: 18,
        font: boldFont,
        color: rgb(0.05, 0.09, 0.16),
      });

      y -= 30;
    }

    function drawMeta() {
      page.drawText("Generated by Apprain COS", {
        x: 40,
        y,
        size: 9,
        font,
        color: rgb(0.4, 0.45, 0.55),
      });

      page.drawText(`Application ID: ${leadId}`, {
        x: 315,
        y,
        size: 8,
        font,
        color: rgb(0.4, 0.45, 0.55),
      });

      y -= 30;
    }

    function drawSection(title: string) {
      ensureSpace(90);

      y -= 10;

      page.drawRectangle({
        x: 40,
        y: y - 6,
        width: 515,
        height: 24,
        color: rgb(0.9, 0.98, 0.92),
      });

      page.drawText(title, {
        x: 50,
        y,
        size: 11,
        font: boldFont,
        color: rgb(0.05, 0.35, 0.16),
      });

      y -= 32;
    }

    function drawField(label: string, value: any, x: number, width = 240) {
      page.drawText(label, {
        x,
        y,
        size: 8,
        font,
        color: rgb(0.35, 0.39, 0.47),
      });

      page.drawText(text(value), {
        x,
        y: y - 14,
        size: 9,
        font: boldFont,
        color: rgb(0.05, 0.09, 0.16),
      });

      page.drawLine({
        start: { x, y: y - 20 },
        end: { x: x + width, y: y - 20 },
        thickness: 0.5,
        color: rgb(0.8, 0.84, 0.9),
      });
    }

    function drawRow(
      leftLabel: string,
      leftValue: any,
      rightLabel: string,
      rightValue: any,
    ) {
      ensureSpace(70);

      drawField(leftLabel, leftValue, 50);
      drawField(rightLabel, rightValue, 315);

      y -= 42;
    }

    function drawTableHeader(headers: string[], x: number, widths: number[]) {
      let currentX = x;

      headers.forEach((header, index) => {
        page.drawRectangle({
          x: currentX,
          y,
          width: widths[index],
          height: 24,
          borderWidth: 0.7,
          borderColor: rgb(0.2, 0.2, 0.2),
          color: rgb(0.94, 0.98, 0.94),
        });

        page.drawText(header, {
          x: currentX + 5,
          y: y + 8,
          size: 7,
          font: boldFont,
          color: rgb(0.05, 0.09, 0.16),
        });

        currentX += widths[index];
      });

      y -= 24;
    }

    function drawTableRow(values: any[], x: number, widths: number[]) {
      let currentX = x;

      values.forEach((value, index) => {
        page.drawRectangle({
          x: currentX,
          y,
          width: widths[index],
          height: 26,
          borderWidth: 0.7,
          borderColor: rgb(0.2, 0.2, 0.2),
        });

        page.drawText(text(value), {
          x: currentX + 5,
          y: y + 9,
          size: 7,
          font,
          color: rgb(0.05, 0.09, 0.16),
        });

        currentX += widths[index];
      });

      y -= 26;
    }

    function addApplicationPage() {
      drawTitle("Brokerage Account Opening Application");
      drawMeta();

      drawSection("Customer Information");
      drawRow(
        "Full Name",
        lead?.fullName || "Test Brokerage Customer",
        "Mobile",
        lead?.mobileNo,
      );
      drawRow(
        "Document Number",
        lead?.documentNumber || "NID-123456789",
        "Date of Birth",
        lead?.dateOfBirth || "1990-01-01",
      );
      drawRow(
        "Address",
        lead?.address || "Dhaka, Bangladesh",
        "KYC Status",
        lead?.kycStatus,
      );

      drawSection("Account Information");
      drawRow(
        "BO Type",
        extraData?.boType || "Single",
        "Trading Account Type",
        extraData?.tradingAccountType || "Regular",
      );
      drawRow(
        "BO ID No.",
        extraData?.boIdNo || "1200000000000001",
        "Account Type",
        extraData?.accountType || "Non-Margin",
      );

      drawSection("Bank Information");
      drawRow(
        "Bank Name",
        extraData?.bankName || "DBBL",
        "Account Number",
        extraData?.accountNumber || "123456789",
      );
      drawRow(
        "Routing Number",
        extraData?.routingNumber || "090000000",
        "Branch",
        extraData?.branchName || "Motijheel",
      );

      drawSection("KYC Profile");
      drawRow(
        "Father Name",
        extraData?.fatherName || "Father Name",
        "Mother Name",
        extraData?.motherName || "Mother Name",
      );
      drawRow(
        "Occupation",
        extraData?.occupation || "Business",
        "Monthly Income",
        extraData?.monthlyIncome || "100000",
      );
      drawRow(
        "Source of Fund",
        extraData?.sourceOfFund || "Business Income",
        "Risk Profile",
        extraData?.riskProfile || "Moderate",
      );

      drawSection("Nominee Information");
      drawRow(
        "Nominee Name",
        extraData?.nomineeName || "Nominee Person",
        "Relation",
        extraData?.nomineeRelation || "Brother",
      );
      drawRow(
        "Nominee Mobile",
        extraData?.nomineeMobile || "01711111111",
        "Nominee NID",
        extraData?.nomineeNid || "987654321",
      );

      drawSection("Declaration");
      ensureSpace(130);

      page.drawText(
        "I/We confirm that the information provided in this application is true and complete. I/We agree to update the brokerage house if any information changes.",
        {
          x: 50,
          y,
          size: 9,
          font,
          maxWidth: 490,
          lineHeight: 13,
          color: rgb(0.15, 0.18, 0.24),
        },
      );

      y -= 70;

      drawField("Applicant Signature", "", 50, 220);
      drawField("Authorized Officer", "", 315, 220);
    }

    function addTransactionProfilePage() {
      addNewPage();

      drawTitle("Transaction Profile");
      drawMeta();

      drawSection("Account Information");
      drawRow(
        "Account Number",
        extraData?.accountNumber || "123456789",
        "Date",
        new Date().toLocaleDateString(),
      );
      drawRow(
        "Title of Account",
        lead?.fullName || "Test Brokerage Customer",
        "BO ID No.",
        extraData?.boIdNo || "1200000000000001",
      );
      drawRow(
        "Type of Account",
        extraData?.boType || "Individual Account",
        "Account Type",
        extraData?.accountType || "Non-Margin",
      );

      drawSection("Deposit Transaction Profile");

      drawTableHeader(
        [
          "Particulars",
          "No. of Transactions",
          "Maximum Amount",
          "Total Monthly Amount",
        ],
        50,
        [190, 105, 110, 110],
      );

      drawTableRow(
        [
          "Cash Deposit",
          extraData?.cashDepositCount || "10",
          extraData?.maxCashDeposit || "50000",
          extraData?.cashDepositAmount || "500000",
        ],
        50,
        [190, 105, 110, 110],
      );

      drawTableRow(
        [
          "Transfer / Deposit by Instruments",
          extraData?.instrumentDepositCount || "5",
          extraData?.maxInstrumentDeposit || "60000",
          extraData?.instrumentDepositAmount || "300000",
        ],
        50,
        [190, 105, 110, 110],
      );

      drawTableRow(
        [
          "Others",
          extraData?.otherDepositCount || "2",
          extraData?.maxOtherDeposit || "25000",
          extraData?.otherDepositAmount || "50000",
        ],
        50,
        [190, 105, 110, 110],
      );

      y -= 12;

      drawSection("Withdrawal Transaction Profile");

      drawTableHeader(
        [
          "Particulars",
          "No. of Transactions",
          "Maximum Amount",
          "Total Monthly Amount",
        ],
        50,
        [190, 105, 110, 110],
      );

      drawTableRow(
        [
          "Transfer / Payment by Instruments",
          extraData?.instrumentWithdrawalCount || "5",
          extraData?.maxWithdrawalAmount || "100000",
          extraData?.totalWithdrawalAmount || "300000",
        ],
        50,
        [190, 105, 110, 110],
      );

      drawTableRow(
        [
          "Others",
          extraData?.otherWithdrawalCount || "1",
          extraData?.maxOtherWithdrawal || "20000",
          extraData?.otherWithdrawalAmount || "20000",
        ],
        50,
        [190, 105, 110, 110],
      );

      y -= 12;

      drawSection("Securities Transaction");

      drawTableHeader(
        [
          "Particulars",
          "No. of Transactions Daily",
          "Daily Volume",
          "Monthly Volume",
        ],
        50,
        [120, 135, 130, 130],
      );

      drawTableRow(
        [
          "Buy",
          extraData?.dailyBuyCount || "3",
          extraData?.dailyBuyVolume || "200000",
          extraData?.monthlyBuyVolume || "2000000",
        ],
        50,
        [120, 135, 130, 130],
      );

      drawTableRow(
        [
          "Sell",
          extraData?.dailySellCount || "3",
          extraData?.dailySellVolume || "200000",
          extraData?.monthlySellVolume || "2000000",
        ],
        50,
        [120, 135, 130, 130],
      );

      y -= 12;

      drawSection("Source of Fund");
      drawRow(
        "Source of Fund",
        extraData?.sourceOfFund || "Business Income",
        "Risk Profile",
        extraData?.riskProfile || "Moderate",
      );

      drawSection("Declaration");

      page.drawText(
        "I/We acknowledge that the transaction limits mentioned above represent my/our usual transaction profile. I/We agree to update this profile if my/our transaction behavior changes.",
        {
          x: 50,
          y,
          size: 9,
          font,
          maxWidth: 490,
          lineHeight: 13,
          color: rgb(0.15, 0.18, 0.24),
        },
      );

      y -= 70;

      drawField("Applicant Signature", "", 50, 220);
      drawField(
        "Applicant Name",
        lead?.fullName || "Test Brokerage Customer",
        315,
        220,
      );
    }

    addApplicationPage();
    addTransactionProfilePage();

    const pdfBytes = await pdfDoc.save();

    const pdfBlob = new Blob([pdfBytes.slice().buffer], {
      type: "application/pdf",
    });

    saveAs(pdfBlob, `Brokerage_Application_${leadId}.pdf`);
  }

  ////////////////////////////////////
  async function downloadKycProfilePdf() {
    const pdfDoc = await PDFDocument.create();

    const pageWidth = 595;
    const pageHeight = 842;

    let page = pdfDoc.addPage([pageWidth, pageHeight]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    function value(v: any, fallback = "-") {
      return String(v || fallback);
    }

    function drawBox(x: number, y: number, w: number, h = 18) {
      page.drawRectangle({
        x,
        y,
        width: w,
        height: h,
        borderWidth: 1,
        borderColor: rgb(0, 0, 0),
      });
    }

    function drawText(
      label: string,
      x: number,
      y: number,
      size = 9,
      bold = false,
    ) {
      page.drawText(label, {
        x,
        y,
        size,
        font: bold ? boldFont : font,
        color: rgb(0, 0, 0),
      });
    }

    function drawField(
      label: string,
      valueText: any,
      x: number,
      y: number,
      w = 260,
    ) {
      drawText(label, x, y + 5, 9, true);
      drawBox(x + 125, y, w, 18);
      drawText(value(valueText), x + 132, y + 5, 8);
    }

    function addNewPage() {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
    }

    function addCompanyHeader(title: string) {
      drawText("MEGHNA BANK", 40, 780, 16, true);
      drawText("SECURITIES LIMITED", 40, 762, 16, true);
      drawText(
        "Room # 626 (5th Floor), 9/E Motijheel C/A, Dhaka-1000",
        40,
        746,
        8,
      );
      drawText(
        "DSE TREC No. 124, BSEC Reg. No. 3.1/DSE-124/2015/537",
        40,
        734,
        8,
      );

      page.drawRectangle({
        x: 35,
        y: 705,
        width: 525,
        height: 20,
        color: rgb(0.02, 0.03, 0.12),
      });

      drawText(title, title === "KYC PROFILE" ? 260 : 235, 711, 12, true);
    }

    function addKycProfilePage() {
      addCompanyHeader("KYC PROFILE");

      drawBox(395, 752, 75, 85);
      drawText("Photograph of", 410, 800, 7);
      drawText("1st Account Holder", 405, 790, 7);

      drawBox(480, 752, 75, 85);
      drawText("Photograph of", 495, 800, 7);
      drawText("Joint Account Holder", 490, 790, 7);

      drawField(
        "Client Code :",
        extraData?.clientCode || "000001",
        40,
        645,
        90,
      );

      drawText("Account Type :", 330, 650, 9, true);
      drawBox(410, 644, 60, 18);
      drawText(extraData?.accountType || "Margin", 425, 649, 8);
      drawBox(485, 644, 70, 18);
      drawText(extraData?.tradingAccountType || "Non-Margin", 493, 649, 8);

      drawField(
        "Name of Account Holder",
        lead?.fullName || "Test Brokerage Customer",
        40,
        600,
        390,
      );
      drawField(
        "Name of Joint Acc. Holder",
        extraData?.jointAccountName || "",
        40,
        565,
        390,
      );
      drawField(
        "BO ID No.",
        extraData?.boIdNo || "1200000000000001",
        40,
        530,
        220,
      );

      drawBox(40, 320, 515, 190);
      drawText("Source of Income :", 55, 490, 11, true);

      drawText("Service:", 55, 460, 9, true);
      drawBox(145, 452, 75, 18);
      drawText("Government", 158, 457, 8);
      drawBox(235, 452, 75, 18);
      drawText("Private", 258, 457, 8);

      drawField(
        "(i) Name of the Organization",
        extraData?.organizationName || "ABC Company Ltd.",
        100,
        425,
        310,
      );
      drawField(
        "(ii) Designation",
        extraData?.designation || "Manager",
        100,
        395,
        310,
      );
      drawField(
        "(iii) Monthly Income",
        extraData?.monthlyIncome || "100000",
        100,
        365,
        310,
      );

      drawText(
        "(Proof of service i.e. Salary/Employment Certificate MUST be provided)",
        140,
        342,
        8,
      );

      drawText("Business:", 55, 305, 9, true);
      drawBox(145, 297, 75, 18);
      drawText("Public", 168, 302, 8);
      drawBox(235, 297, 75, 18);
      drawText("Private", 258, 302, 8);

      drawField(
        "(i) Name of the Business",
        extraData?.businessName || "Sample Trading",
        120,
        270,
        310,
      );
      drawField(
        "(ii) Details of the Business",
        extraData?.businessDetails || "Stock trading and investment",
        120,
        240,
        310,
      );

      drawText(
        "(Proof of business i.e. TIN number/Trade License MUST be provided)",
        140,
        218,
        8,
      );

      drawText(
        "Others: Please specify .................................................................",
        55,
        190,
        9,
      );

      let y = 155;

      const ids = [
        ["Passport No.", extraData?.passportNo || "P1234567"],
        ["Voter ID Card No.", extraData?.voterIdNo || "V987654321"],
        ["National ID No.", lead?.documentNumber || "1234567890"],
        ["TIN No.", extraData?.tinNo || "TIN-123456"],
        ["VAT Reg. No.", extraData?.vatRegNo || "VAT-987654"],
        ["Driving License No.", extraData?.drivingLicenseNo || "DL-123456"],
      ];

      ids.forEach(([label, val]) => {
        drawText(label, 45, y + 5, 8, true);
        drawBox(150, y, 185, 16);
        drawText(value(val), 155, y + 5, 7);

        drawText("Photocopy Obtained", 360, y + 5, 8);
        drawBox(455, y, 25, 16);
        drawText("Yes", 460, y + 5, 7);
        drawBox(490, y, 25, 16);
        drawText("No", 497, y + 5, 7);

        y -= 25;
      });

      drawText("In case of non-resident & Foreigner", 45, y + 5, 8, true);
      drawText("a) Reasons for opening the Account", 250, y + 5, 8, true);
      drawBox(400, y, 145, 16);

      y -= 25;

      drawText("b) Type of Visa", 250, y + 5, 8, true);
      drawBox(360, y, 18, 16);
      drawText("Resident", 385, y + 5, 8);
      drawBox(430, y, 18, 16);
      drawText("Work", 455, y + 5, 8);
      drawText("Valid upto", 490, y + 5, 8);
      drawBox(535, y, 40, 16);

      y -= 30;

      drawText(
        "Account Holder's Profession/Type of business:",
        45,
        y + 5,
        8,
        true,
      );
      drawBox(280, y, 275, 16);
      drawText(extraData?.occupation || "Business", 285, y + 5, 7);
    }

    function addTransactionProfilePage() {
      addNewPage();
      addCompanyHeader("TRANSACTION PROFILE");

      drawText("Account Number", 45, 655, 9, true);
      drawBox(170, 648, 180, 18);
      drawText(extraData?.accountNumber || "123456789", 176, 653, 8);

      drawText("Date:", 405, 655, 9, true);
      drawBox(445, 648, 90, 18);
      drawText(new Date().toLocaleDateString(), 450, 653, 8);

      drawText("Title of Account", 45, 620, 9, true);
      drawBox(170, 613, 365, 18);
      drawText(lead?.fullName || "Test Brokerage Customer", 176, 618, 8);

      drawText("Second Applicant", 90, 590, 8);
      drawBox(170, 583, 365, 18);
      drawText(extraData?.jointAccountName || "-", 176, 588, 8);

      drawText("Type of Account", 45, 555, 9, true);
      drawBox(170, 548, 14, 14);
      drawText("Individual Account", 190, 551, 8);
      drawBox(330, 548, 14, 14);
      drawText("Margin", 350, 551, 8);
      drawBox(500, 548, 14, 14);
      drawText("NRB", 520, 551, 8);

      drawBox(170, 525, 14, 14);
      drawText("Joint Account", 190, 528, 8);
      drawBox(330, 525, 14, 14);
      drawText("Non-Margin", 350, 528, 8);

      drawText("BO ID No.", 45, 495, 9, true);
      drawBox(170, 488, 290, 18);
      drawText(extraData?.boIdNo || "1200000000000001", 176, 493, 8);

      function table(
        title: string,
        startY: number,
        rows: string[][],
        showTotal: string,
      ) {
        drawText(title, 45, startY + 58, 9, true);

        const x = 45;
        let y = startY;
        const widths = [190, 105, 130, 90];

        const headers = [
          "Particulars",
          "No. of Transactions",
          "Maximum Amount",
          "Total Monthly",
        ];

        let cx = x;
        headers.forEach((h, i) => {
          drawBox(cx, y, widths[i], 24);
          drawText(h, cx + 5, y + 9, 7, true);
          cx += widths[i];
        });

        y -= 24;

        rows.forEach((r) => {
          cx = x;
          r.forEach((v, i) => {
            drawBox(cx, y, widths[i], 24);
            drawText(v, cx + 5, y + 9, 7);
            cx += widths[i];
          });
          y -= 24;
        });

        drawBox(x, y, widths[0] + widths[1] + widths[2], 24);
        drawText(showTotal, x + 300, y + 9, 7, true);
        drawBox(x + widths[0] + widths[1] + widths[2], y, widths[3], 24);
      }

      table(
        "Deposit",
        425,
        [
          [
            "Cash Deposit",
            extraData?.cashDepositCount || "10",
            extraData?.maxCashDeposit || "50000",
            extraData?.cashDepositAmount || "500000",
          ],
          [
            "Transfer/deposit by Instruments",
            extraData?.instrumentDepositCount || "5",
            extraData?.maxInstrumentDeposit || "60000",
            extraData?.instrumentDepositAmount || "300000",
          ],
          [
            "Others",
            extraData?.otherDepositCount || "2",
            extraData?.maxOtherDeposit || "25000",
            extraData?.otherDepositAmount || "50000",
          ],
        ],
        "Total Deposit approx.",
      );

      table(
        "Withdrawal",
        285,
        [
          [
            "Transfer/payment by Instruments",
            extraData?.instrumentWithdrawalCount || "5",
            extraData?.maxWithdrawalAmount || "100000",
            extraData?.totalWithdrawalAmount || "300000",
          ],
          [
            "Others",
            extraData?.otherWithdrawalCount || "1",
            extraData?.maxOtherWithdrawal || "20000",
            extraData?.otherWithdrawalAmount || "20000",
          ],
        ],
        "Total Withdrawal approx.",
      );

      drawText("Securities Transaction", 45, 185, 9, true);

      let sy = 145;
      const sx = 45;
      const sw = [90, 150, 150, 125];

      [
        "Particulars",
        "No. of Transactions Daily",
        "Daily Volume",
        "Monthly Volume",
      ].forEach((h, i) => {
        drawBox(sx + sw.slice(0, i).reduce((a, b) => a + b, 0), sy, sw[i], 24);
        drawText(
          h,
          sx + sw.slice(0, i).reduce((a, b) => a + b, 0) + 5,
          sy + 9,
          7,
          true,
        );
      });

      sy -= 24;

      [
        [
          "Buy",
          extraData?.dailyBuyCount || "3",
          extraData?.dailyBuyVolume || "200000",
          extraData?.monthlyBuyVolume || "2000000",
        ],
        [
          "Sell",
          extraData?.dailySellCount || "3",
          extraData?.dailySellVolume || "200000",
          extraData?.monthlySellVolume || "2000000",
        ],
      ].forEach((row) => {
        let x = sx;
        row.forEach((v, i) => {
          drawBox(x, sy, sw[i], 24);
          drawText(v, x + 5, sy + 9, 7);
          x += sw[i];
        });
        sy -= 24;
      });

      drawText("Sources of Fund", 45, 70, 9, true);
      drawBox(170, 63, 365, 18);
      drawText(extraData?.sourceOfFund || "Business Income", 176, 68, 8);

      drawText("Signature", 45, 30, 8, true);
      drawBox(170, 22, 150, 28);
      drawText("Name", 340, 30, 8, true);
      drawBox(385, 22, 150, 28);
      drawText(lead?.fullName || "Test Brokerage Customer", 390, 32, 7);
    }

    addKycProfilePage();
    addTransactionProfilePage();

    const pdfBytes = await pdfDoc.save();

    const pdfBlob = new Blob([pdfBytes.slice().buffer], {
      type: "application/pdf",
    });

    saveAs(pdfBlob, `KYC_Profile_${leadId}.pdf`);
  }

  /////////////////////////////////

  async function downloadApplicationPdf2() {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    function drawCard(
      label: string,
      value: any,
      x: number,
      y: number,
      w = 240,
      h = 46,
    ) {
      page.drawRectangle({
        x,
        y,
        width: w,
        height: h,
        borderWidth: 1,
        borderColor: rgb(0, 0, 0),
        color: rgb(0.98, 0.98, 0.98),
      });

      page.drawText(label, {
        x: x + 10,
        y: y + h - 15,
        size: 7,
        font,
        color: rgb(0.35, 0.35, 0.45),
      });

      const text = String(value || "-");

      page.drawText(text.length > 34 ? text.substring(0, 34) + "..." : text, {
        x: x + 10,
        y: y + 12,
        size: 8,
        font: boldFont,
        color: rgb(0, 0, 0),
      });
    }

    async function addImageCard(
      url: string,
      x: number,
      y: number,
      title: string,
    ) {
      page.drawRectangle({
        x,
        y,
        width: 155,
        height: 120,
        borderWidth: 1,
        borderColor: rgb(0, 0, 0),
        color: rgb(0.98, 0.98, 0.98),
      });

      page.drawText(title, {
        x: x + 8,
        y: y + 104,
        size: 8,
        font: boldFont,
      });

      if (!url) return;

      try {
        const res = await fetch(url);
        const imageBytes = await res.arrayBuffer();
        const contentType = res.headers.get("content-type") || "";

        const image =
          contentType.includes("png") || url.toLowerCase().includes(".png")
            ? await pdfDoc.embedPng(imageBytes)
            : await pdfDoc.embedJpg(imageBytes);

        page.drawImage(image, {
          x: x + 8,
          y: y + 10,
          width: 139,
          height: 85,
        });
      } catch {
        page.drawText("Image unavailable", {
          x: x + 25,
          y: y + 50,
          size: 8,
          font,
          color: rgb(0.5, 0.5, 0.5),
        });
      }
    }

    let y = 800;

    page.drawText("Brokerage Application", {
      x: 40,
      y,
      size: 22,
      font: boldFont,
    });

    y -= 35;

    page.drawText("KYC Images", {
      x: 40,
      y,
      size: 13,
      font: boldFont,
    });

    y -= 130;

    await addImageCard(kycData?.selfieImageUrl, 40, y, "Selfie");
    await addImageCard(kycData?.frontImageUrl, 220, y, "Document Front");
    await addImageCard(kycData?.backImageUrl, 400, y, "Document Back");

    y -= 65;

    drawCard("Mobile", lead?.mobileNo, 40, y);
    drawCard("Full Name", lead?.fullName, 315, y);

    y -= 55;
    drawCard("Document Number", lead?.documentNumber, 40, y);
    drawCard("Date of Birth", lead?.dateOfBirth, 315, y);

    y -= 55;
    drawCard("KYC Status", lead?.kycStatus, 40, y);
    drawCard("Application Status", lead?.leadStatus, 315, y);

    y -= 55;
    drawCard("Face Match Status", lead?.faceMatchStatus, 40, y);
    drawCard(
      "Face Match Score",
      lead?.faceMatchScore != null
        ? `${Number(lead.faceMatchScore).toFixed(2)}%`
        : "-",
      315,
      y,
    );

    y -= 55;

    page.drawText("Brokerage Information", {
      x: 40,
      y,
      size: 13,
      font: boldFont,
    });

    y -= 50;

    drawCard("Father Name", extraData?.fatherName, 40, y);
    drawCard("Mother Name", extraData?.motherName, 315, y);

    y -= 55;
    drawCard("Occupation", extraData?.occupation, 40, y);
    drawCard("BO Type", extraData?.boType, 315, y);

    y -= 55;
    drawCard("Trading Account Type", extraData?.tradingAccountType, 40, y);
    drawCard("Bank Name", extraData?.bankName, 315, y);

    y -= 55;
    drawCard("Account Number", extraData?.accountNumber, 40, y);
    drawCard("Routing Number", extraData?.routingNumber, 315, y);

    y -= 55;
    drawCard("Nominee Name", extraData?.nomineeName, 40, y);
    drawCard("Nominee Relation", extraData?.nomineeRelation, 315, y);

    y -= 55;
    drawCard("Nominee Mobile", extraData?.nomineeMobile, 40, y);
    drawCard("Risk Profile", extraData?.riskProfile, 315, y);

    y -= 55;
    drawCard("FATCA Declaration", extraData?.fatcaDeclaration, 40, y);

    page.drawText("Generated by Apprain COS", {
      x: 40,
      y: 35,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });

    const pdfBytes = await pdfDoc.save();

    const pdfBlob = new Blob([pdfBytes.slice().buffer], {
      type: "application/pdf",
    });

    saveAs(pdfBlob, `Brokerage_Application_${leadId}.pdf`);
  }

  if (loading) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-gray-100">
        Loading application...
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-gray-100 p-6">
      <div className="mx-auto max-w-5xl rounded-2xl bg-white p-6 shadow">
        <a
          href="/admin/brokerage-applications"
          className="text-sm text-blue-600"
        >
          ← Back to Brokerage Applications
        </a>

        <div className="mt-4 flex items-center justify-between">
          <h1 className="text-3xl font-bold">Brokerage Application Details</h1>

          <div className="flex gap-3">
            <button
              onClick={approveApplication}
              className="rounded bg-green-600 px-4 py-2 text-sm font-semibold text-white"
            >
              Approve
            </button>

            <button
              onClick={rejectApplication}
              className="rounded bg-red-600 px-4 py-2 text-sm font-semibold text-white"
            >
              Reject
            </button>

            <button
              onClick={downloadKycProfilePdf}
              className="rounded bg-green-600 px-4 py-2 text-sm font-semibold text-white"
            >
              Download KYC Profile
            </button>

            <button
              onClick={downloadApplicationPdf}
              className="rounded bg-black px-4 py-2 text-sm font-semibold text-white"
            >
              Download PDF
            </button>
          </div>
        </div>

        <section className="mt-8">
          <h2 className="mb-4 text-xl font-semibold">KYC Images</h2>

          {kycData ? (
            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
              <ImageCard
                title="Selfie"
                src={kycData.selfieImageUrl}
                onClick={() => setSelectedImage(kycData.selfieImageUrl)}
              />

              <ImageCard
                title="Document Front"
                src={kycData.frontImageUrl}
                onClick={() => setSelectedImage(kycData.frontImageUrl)}
              />

              <ImageCard
                title="Document Back"
                src={kycData.backImageUrl}
                onClick={() => setSelectedImage(kycData.backImageUrl)}
              />
            </div>
          ) : (
            <p className="rounded bg-yellow-50 p-4 text-sm">
              No KYC images found.
            </p>
          )}
        </section>

        <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">
          <Info label="Mobile" value={lead?.mobileNo} />
          <Info label="Full Name" value={lead?.fullName} />
          <Info label="Document Number" value={lead?.documentNumber} />
          <Info label="Date of Birth" value={lead?.dateOfBirth} />
          <Info label="KYC Status" value={lead?.kycStatus} />
          <Info label="Application Status" value={lead?.leadStatus} />
          <Info label="Face Match Status" value={lead?.faceMatchStatus} />
          <Info
            label="Face Match Score"
            value={
              lead?.faceMatchScore != null
                ? `${Number(lead.faceMatchScore).toFixed(2)}%`
                : "-"
            }
          />
        </div>

        <section className="mt-8">
          <h2 className="mb-4 text-xl font-semibold">Brokerage Information</h2>

          {extraData ? (
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <Info label="Father Name" value={extraData.fatherName} />
              <Info label="Mother Name" value={extraData.motherName} />
              <Info label="Occupation" value={extraData.occupation} />
              <Info label="BO Type" value={extraData.boType} />
              <Info
                label="Trading Account Type"
                value={extraData.tradingAccountType}
              />
              <Info label="Bank Name" value={extraData.bankName} />
              <Info label="Account Number" value={extraData.accountNumber} />
              <Info label="Routing Number" value={extraData.routingNumber} />
              <Info label="Nominee Name" value={extraData.nomineeName} />
              <Info
                label="Nominee Relation"
                value={extraData.nomineeRelation}
              />
              <Info label="Nominee Mobile" value={extraData.nomineeMobile} />
              <Info label="Risk Profile" value={extraData.riskProfile} />
              <Info
                label="FATCA Declaration"
                value={extraData.fatcaDeclaration}
              />
            </div>
          ) : (
            <p className="rounded bg-yellow-50 p-4 text-sm">
              No brokerage information submitted yet.
            </p>
          )}
        </section>
      </div>

      {selectedImage && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"
          onClick={() => setSelectedImage(null)}
        >
          <div className="max-h-[90vh] max-w-5xl rounded bg-white p-3">
            <img
              src={selectedImage}
              alt="Preview"
              className="max-h-[85vh] max-w-full rounded object-contain"
            />
          </div>
        </div>
      )}
    </main>
  );
}

function Info({ label, value }: { label: string; value: any }) {
  return (
    <div className="rounded-lg border bg-gray-50 p-4">
      <p className="text-sm text-gray-500">{label}</p>
      <p className="mt-1 font-semibold text-gray-900">{value || "-"}</p>
    </div>
  );
}

function ImageCard({
  title,
  src,
  onClick,
}: {
  title: string;
  src: string;
  onClick?: () => void;
}) {
  return (
    <div className="rounded-lg border bg-gray-50 p-4">
      <p className="mb-2 text-sm font-semibold text-gray-700">{title}</p>

      {src ? (
        <img
          src={src}
          alt={title}
          onClick={onClick}
          className="h-48 w-full cursor-pointer rounded border object-cover"
        />
      ) : (
        <div className="flex h-48 items-center justify-center rounded border bg-white text-sm text-gray-400">
          No image
        </div>
      )}
    </div>
  );
}
