export enum LeadStatus {
    LEAD_CREATED = 'LEAD_CREATED',
    OTP_VERIFIED = 'OTP_VERIFIED',
    KYC_STARTED = 'KYC_STARTED',
    KYC_COMPLETED = 'KYC_COMPLETED',
    PROFILE_ENRICHED = 'PROFILE_ENRICHED',
    READY_FOR_REVIEW = 'READY_FOR_REVIEW',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
}